"""empty message

Revision ID: c6007059eed6
Revises: 
Create Date: 2018-03-27 22:23:16.661763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6007059eed6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Stations',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('location_latitude', sa.Float(), nullable=False),
    sa.Column('location_longitude', sa.Float(), nullable=False),
    sa.Column('banking', sa.Boolean(), nullable=False),
    sa.Column('bonus', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stations')
    # ### end Alembic commands ###
